# etcd 集群配置
etcd:
  endpoints:
    - etcd:2379
  dial_timeout: 5s
  username: ""
  password: ""
  recover_time: 5s
balancer:
  "produce":
    "chatsvr":
      balancer_type: "random"
      dynamic_config:
        key: "chat-user-id"
        cache: true
        cache_type: "lru"
        cache_size: 6000
        auto_flush: true
      static_config:
        key: "user-id"
      consistent_hash_config:
        hash_func: "crc32"
        replicas: 10
        key: "hash-key"
      custom_config:
        "test": "test"
  "test":
redis:
  "produce":
    addrs:
      - "redis:6379"
      - "localhost:9002"
      - "localhost:9003"
      - "localhost:9004"
      - "localhost:9005"
      - "localhost:9006"
    username: ""
    password: ""
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s