# etcd 集群配置
etcd:
  endpoints:
    - etcd:2379
  dial_timeout: 5s
  username: ""
  password: ""
balancer:
  rules:
    "matchsvr":
      balancer_type: "consistent-hash"
      namespace: "produce"
      consistent_hash_config:
        hash_func: "crc32"
        replicas: 1000
        key: "hash-key"
    "chatsvr":
      balancer_type: "static"
      namespace: "produce"
      static_config:
        expire: 0s
        key: "user-id"
redis:
  addrs:
    - "9.134.61.100:9001"
    - "9.134.61.100:9002"
    - "9.134.61.100:9003"
    - "9.134.61.100:9004"
    - "9.134.61.100:9005"
    - "9.134.61.100:9006"
  username: ""
  password: ""
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
server:
  "server-1":
    endpoint:
      name: "chatsvr"
      namespace: "produce"
      ip: "server-1"
      port: "50051"
      weight: 1
      wants_type: all_match
      wants:
        - match_type: prefix
          pattern: "user1"
    lease: 1
  "server-2":
    endpoint:
      name: "chatsvr"
      namespace: "produce"
      ip: "server-2"
      port: "50052"
      weight: 1
      wants_type: all_not_match
      wants:
        - match_type: prefix
          pattern: "user1"
    lease: 1
  "server-3":
    endpoint:
      name: "matchsvr"
      namespace: "produce"
      ip: "server-3"
      port: "50053"
      weight: 1
    lease: 1