global:
  scrape_interval:     1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
  # - job_name: 'server'
  #   static_configs:
  #   - targets: ['server-1:8080','server-2:8080', 'server-3:8080']
  - job_name: 'client'
    static_configs:
    - targets: ['9.134.61.100:8081']